In [1]:
import os
import pandas as pd
import numpy as np
import datetime
import pickle
# pd.set_option('display.max_columns', None)
# pd.set_option("display.max_rows", 50)

import warnings

# Use this filter to ignore the specific FutureWarning
warnings.simplefilter(action='ignore', category=FutureWarning)

target_folder_path = '/Volumes/Database/Original_data'
%cd "{target_folder_path}"

/Volumes/Database/Original_data

### Get correct_datetime_df "open"

In [2]:
open = pd.read_csv("/Volumes/Database/Factor_data/open.csv", index_col=0)

In [3]:
leverage_data = pd.read_table(rf"{target_folder_path}/籌碼資料庫/融資融券.txt", encoding='Big5-HKSCS', low_memory=False)
leverage_data

,公司代碼,簡稱,年月日,融資餘額(張),融資餘額(千元),融資買進(張),融資買進(千元),融資賣出(張),融資賣出(千元),融資現金償還(張),...,借券賣出可使用額度,借券賣出限額,借券賣出(千元)_交易所,融券賣出(千元)_交易所,均價,每股融資成本,每股融券成本,融資維持率,融券維持率,整戶維持率
0,1101,台泥,19910104,13422,993764.88,1935,143267.40,1278,94623.12,34,...,-,-,-,-,74.0400,72.6300,83.6700,169.82,214.82,183.72
1,1101,台泥,19910105,13506,1031993.46,1648,125923.68,1519,116066.79,45,...,-,-,-,-,76.4100,73.0900,82.4800,174.45,204.85,184.39
2,1101,台泥,19910107,12988,934616.48,892,64188.32,1402,100887.92,8,...,-,-,-,-,71.9600,73.0100,82.4800,164.36,217.65,179.15
3,1101,台泥,19910108,12442,858249.16,813,56080.74,1354,93398.92,5,...,-,-,-,-,68.9800,72.7500,82.4800,158.08,227.12,174.67
4,1101,台泥,19910109,12351,871486.56,651,45934.56,739,52143.84,3,...,-,-,-,-,70.5600,72.6300,80.9100,161.77,218.05,175.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7876698,8925,偉盟,20151021,16386,22284.96,0,0.00,0,0.00,0,...,199,36524,0.00,0.00,1.3600,5.0963,2.2720,44.48,317.41,58.36
7876699,8925,偉盟,20151022,16352,20112.96,0,0.00,0,0.00,34,...,195,36524,0.00,0.00,1.2300,5.0963,2.2720,40.23,350.96,54.62
7876700,8925,偉盟,20151023,15916,17666.76,0,0.00,6,6.66,430,...,191,36524,0.00,0.00,1.1100,5.0963,2.2720,36.30,388.90,51.50
7876701,8925,偉盟,20151026,15004,15025.01,0,0.00,712,713.00,200,...,247,36524,0.00,0.00,1.0014,5.0963,2.2720,32.70,431.68,48.97
7876702,8925,偉盟,20151027,14784,13305.60,0,0.00,170,153.00,50,...,277,36524,0.00,0.00,0.9000,5.0963,2.2720,29.43,479.64,46.26

In [5]:
columns_list = leverage_data.columns.tolist()
the_place_start_to_become_numeric = 4
columns_list

['公司代碼',
 '簡稱',
 '年月日',
 '融資餘額(張)',
 '融資餘額(千元)',
 '融資買進(張)',
 '融資買進(千元)',
 '融資賣出(張)',
 '融資賣出(千元)',
 '融資現金償還(張)',
 '融資現金償還(千元)',
 '融資增減(張)',
 '融資增減(千元)',
 '融資增減比率',
 '融資使用率',
 '融資限額',
 '融券餘額(張)',
 '融券餘額(千元)',
 '融券買進(張)',
 '融券買進(千元)',
 '融券賣出(張)',
 '融券賣出(千元)',
 '融券現券償還(張)',
 '融券現券償還(千元)',
 '融券增減(張)',
 '融券增減(千元)',
 '融券增減比率',
 '融券使用率',
 '融券限額',
 '是否可信用交易(Y)',
 '券資比',
 '資券互抵',
 '當日收盤',
 '融資(買+賣)/成交量 %',
 '融券(買+賣)/成交量 %',
 '借券賣出餘額(張)',
 '借券賣出餘額(千元)',
 '借券賣出(張)',
 '借券賣出(千元)',
 '借券賣出庫存異動(張)',
 '借券賣出庫存異動(千元)',
 '借券賣出可使用額度',
 '借券賣出限額',
 '借券賣出(千元)_交易所',
 '融券賣出(千元)_交易所',
 '均價',
 '每股融資成本',
 '每股融券成本',
 '融資維持率',
 '融券維持率',
 '整戶維持率']

In [6]:
leverage_data['年月日'] = pd.to_datetime(leverage_data['年月日'].astype(str).str.strip(), format='%Y%m%d')

string_list = ['公司代碼']
for column_name in string_list:
    leverage_data[column_name] = leverage_data[column_name].str.strip()

numeric_list = [element for element in columns_list[the_place_start_to_become_numeric:] if "發布日" not in element]
for column_name in numeric_list:
    leverage_data[column_name] = leverage_data[column_name].astype(str).str.strip()
    leverage_data[column_name] = pd.to_numeric(leverage_data[column_name], errors='coerce')


leverage_data.rename(columns ={'公司代碼':'symbol', '年月日':'datetime'}, inplace=True)
leverage_data

,symbol,簡稱,datetime,融資餘額(張),融資餘額(千元),融資買進(張),融資買進(千元),融資賣出(張),融資賣出(千元),融資現金償還(張),...,借券賣出可使用額度,借券賣出限額,借券賣出(千元)_交易所,融券賣出(千元)_交易所,均價,每股融資成本,每股融券成本,融資維持率,融券維持率,整戶維持率
0,1101,台泥,1991-01-04,13422,993764.88,1935.0,143267.40,1278.0,94623.12,34.0,...,NaN,NaN,NaN,NaN,74.0400,72.6300,83.670,169.82,214.82,183.72
1,1101,台泥,1991-01-05,13506,1031993.46,1648.0,125923.68,1519.0,116066.79,45.0,...,NaN,NaN,NaN,NaN,76.4100,73.0900,82.480,174.45,204.85,184.39
2,1101,台泥,1991-01-07,12988,934616.48,892.0,64188.32,1402.0,100887.92,8.0,...,NaN,NaN,NaN,NaN,71.9600,73.0100,82.480,164.36,217.65,179.15
3,1101,台泥,1991-01-08,12442,858249.16,813.0,56080.74,1354.0,93398.92,5.0,...,NaN,NaN,NaN,NaN,68.9800,72.7500,82.480,158.08,227.12,174.67
4,1101,台泥,1991-01-09,12351,871486.56,651.0,45934.56,739.0,52143.84,3.0,...,NaN,NaN,NaN,NaN,70.5600,72.6300,80.910,161.77,218.05,175.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7876698,8925,偉盟,2015-10-21,16386,22284.96,0.0,0.00,0.0,0.00,0.0,...,199.0,36524.0,0.0,0.0,1.3600,5.0963,2.272,44.48,317.41,58.36
7876699,8925,偉盟,2015-10-22,16352,20112.96,0.0,0.00,0.0,0.00,34.0,...,195.0,36524.0,0.0,0.0,1.2300,5.0963,2.272,40.23,350.96,54.62
7876700,8925,偉盟,2015-10-23,15916,17666.76,0.0,0.00,6.0,6.66,430.0,...,191.0,36524.0,0.0,0.0,1.1100,5.0963,2.272,36.30,388.90,51.50
7876701,8925,偉盟,2015-10-26,15004,15025.01,0.0,0.00,712.0,713.00,200.0,...,247.0,36524.0,0.0,0.0,1.0014,5.0963,2.272,32.70,431.68,48.97
7876702,8925,偉盟,2015-10-27,14784,13305.60,0.0,0.00,170.0,153.00,50.0,...,277.0,36524.0,0.0,0.0,0.9000,5.0963,2.272,29.43,479.64,46.26

In [8]:
leverage_data.columns = leverage_data.columns.str.replace('/', '')
output_list = [col for col in leverage_data.columns[the_place_start_to_become_numeric:] if col not in 'datetime']
print(len(output_list))
output_list

47

['融資餘額(千元)',
 '融資買進(張)',
 '融資買進(千元)',
 '融資賣出(張)',
 '融資賣出(千元)',
 '融資現金償還(張)',
 '融資現金償還(千元)',
 '融資增減(張)',
 '融資增減(千元)',
 '融資增減比率',
 '融資使用率',
 '融資限額',
 '融券餘額(張)',
 '融券餘額(千元)',
 '融券買進(張)',
 '融券買進(千元)',
 '融券賣出(張)',
 '融券賣出(千元)',
 '融券現券償還(張)',
 '融券現券償還(千元)',
 '融券增減(張)',
 '融券增減(千元)',
 '融券增減比率',
 '融券使用率',
 '融券限額',
 '是否可信用交易(Y)',
 '券資比',
 '資券互抵',
 '當日收盤',
 '融資(買+賣)成交量 %',
 '融券(買+賣)成交量 %',
 '借券賣出餘額(張)',
 '借券賣出餘額(千元)',
 '借券賣出(張)',
 '借券賣出(千元)',
 '借券賣出庫存異動(張)',
 '借券賣出庫存異動(千元)',
 '借券賣出可使用額度',
 '借券賣出限額',
 '借券賣出(千元)_交易所',
 '融券賣出(千元)_交易所',
 '均價',
 '每股融資成本',
 '每股融券成本',
 '融資維持率',
 '融券維持率',
 '整戶維持率']

In [9]:
for column in output_list:
    unstack_ohlcv = leverage_data.reset_index().set_index(['datetime','symbol'])[column].unstack()
    csv_file = os.path.join('/Volumes/Database/Factor_data', f'{column}.csv')
    unstack_ohlcv.to_csv(csv_file)

### check